name: 'Get & Cache Dependencies'
description: 'Get the dependencies via npm and cache them.'
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      id: step-cache
      with:
        path: node_modules
        key: node-cache-${{ hashFiles('**/package-lock.json') }}
    - if: steps.step-cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash