name: 'Get & Cache Dependencies'
description: 'Get the dependencies via npm and cache them.'
inputs:
  caching:
    description: 'To give a user an option to use cache or not'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      if: inputs.caching == 'true'
      id: step-cache
      with:
        path: node_modules
        key: node-cache-${{ hashFiles('**/package-lock.json') }}
    - if: steps.step-cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      id: install
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash