name: Deployment Workflow
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cached-deps
        id: cache-deps
        with:
          caching: 'false'
      - run: echo "Was cached used? ${{ steps.cache-deps.outputs.used-cache }}"
      - run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cached-deps
      - run: npm run test
        id: test-fail
      - if: failure() && steps.test-fail.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: fail-test
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cached-deps
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist-file
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist-file
          path: dist
      - run: ls
      - uses: ./.github/actions/deploy-s3-docker
        id: deploy-site
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: custom-actions-js-hosting
          dist-folder: dist
      - run: |
          echo "Live URL: ${{ steps.deploy-site.outputs.website-url }}"