name: Deployment Workflow
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: step-cache
        with:
          path: node_modules
          key: node-cache-${{ hashFiles('**/package-lock.json') }}
      - if: steps.step-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: step-cache
        with:
          path: node_modules
          key: node-cache-${{ hashFiles('**/package-lock.json') }}
      - if: steps.step-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run test
        id: test-fail
      - if: failure() && steps.test-fail.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: fail-test
          path: test.json
  build:
    runs-on: ubuntu-latest
  deploy:
    runs-on: ubuntu-latest